language: python
python:
- '3.5'
install: pip install -r requirements.txt
script: py.test
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
env:
  global:
  - ENCRYPTION_LABEL: 3e8c259749ef
  - COMMIT_AUTHOR_EMAIL: voidfiles@gmail.com
before_install:
- openssl aes-256-cbc -K $encrypted_1dbde6ec09a5_key -iv $encrypted_1dbde6ec09a5_iv
  -in deploy-key.enc -out deploy-key -d
